spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        default_batch_fetch_size: 100
        format_sql: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/webservice
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    org.hiberante.SQL: debug